
[window]
padding = { x = 15, y = 0 }
opacity = 0.85

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"

[general]
import = [
    # "~/.config/alacritty/themes/themes/everforest_dark.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
