[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
padding = { x = 15, y = 0 }
opacity = 0.85

[font]
size = 10.5

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Semibold"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Regular Italic"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font"
style = "Semibold Italic"
